# Generated by Django 4.2.6 on 2023-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_assigned_task_assigned_task_assigned_user_user_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
