# Generated by Django 4.2.6 on 2023-12-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_team_teammodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammodel",
            name="team",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="TeamModel",
        ),
    ]
