# Generated by Django 4.2.6 on 2023-12-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
