# Generated by Django 4.2.6 on 2023-12-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_priority_alter_task_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('NC', 'Not Completed')], default='NC', max_length=2),
        ),
    ]
