# Generated by Django 4.2.6 on 2023-12-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_new_task_task_dependency_team_task_user_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_task',
            name='status',
            field=models.CharField(default='Not Started', max_length=100),
        ),
    ]
