# Generated by Django 4.2.6 on 2023-12-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_new_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
    ]