# Generated by Django 4.2.6 on 2023-12-12 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_time_log_remove_user_task_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_log',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]