# Generated by Django 4.2.6 on 2023-12-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_time_log_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]