# Generated by Django 4.2.6 on 2023-12-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_status'),
        ('tasks', '0012_alter_time_log_timestamp'),
    ]

    operations = [
    ]
